### ISSUE TITLE
Clean up wiki

### ISSUE THREAD

**Issue by LucPrestin** [LucPrestin/Hidden-Modularity#33]
The code was already merged into main, what remains is noting a hypothesis and the gained insights

---

## Conditions of satisfaction

- [ ] Should have pages for used methods
  - [ ] Message Graph
  - [ ] Message Category Graph
- [ ] Update Home with all needed links
- [ ] Should have a wiki page for each of the traced modules
  - [ ] zero divide (#4)
  - [ ] morph opening (#7)
  - [ ] fetching google with accessing content (#16)
  - [ ] fetching google without accessing content (#58)
  - [ ] code browser opening (#24)
  - [ ] Code browser closing through click event
  - [ ] layout recalculation
  - [ ] object explorer opening (#29)

**Each wiki page should have**:
  - a Hypothesis
  - a Description
  - screenshots of the message graph
  - an explanation of the message graph
  - any other gained insights
  - screenshots of the graph

---

**Comment by LucPrestin** [comment]
Contents moved to #61
