### ISSUE TITLE
Trace morph drawing

### ISSUE THREAD

**Issue by LucPrestin** [LucPrestin/Hidden-Modularity#7]
As a user, I'd like to know what happens if a morph gets drawn

---

**Describe the solution you'd like**

- Trace the behavior of `drawOn:`
- Look into the data gathered by the TraceDebugger
- Find out which modules communicate with one another

**Hints & Thoughts**

- `drawOn:` gets called whenever the morph or its parent (like the world) changes. This could lead to potentially huge amounts of TraceDebuggers opening... May have to be careful with that.

**TODOs**

- [x] extract data from the trace debugger
- [x] extract a message graph from the callstack
- [x] note hypothesis, what seem reasonable clusters
- [x] try using a forces simulation on the message graph
- [x] document the findings
- [x] deploy visualization with github pages
